# Not exactly the same as SRResNet in <Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network>
# With 16 Residual blocks w/o BN

#### general settings
name: 100_JASRNetx8_Voxceleb1
use_tb_logger: true
model: sr
distortion: sr
scale: 8
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: VoxCeleb1
    mode: VoxCeleb1
    dataroot_GT: /data2/lbxie/Superface/sisr_train_128_wval.lmdb
    dataroot_LQ: /data2/lbxie/Superface/sisr_train_16_wval.lmdb

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: VoxCeleb1_test
    mode: LQGT
    dataroot_GT: /data2/lbxie/Superface/sisr_val_128
    dataroot_LQ: /data2/lbxie/Superface/sisr_val_16

#### network structures
network_G:
  which_model_G: JASRNet
  n_Parts: 68
  n_resblocks: 32
  n_feats: 128
  scale: 8
  rgb_range: 1
  n_colors: 3

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 1000000
  warmup_iter: -1  # no warm up
  T_period: [250000, 250000, 250000, 250000]
  restarts: [250000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
