# Not exactly the same as SRResNet in <Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network>
# With 16 Residual blocks w/o BN

#### general settings
name: 100_JASRNetx8_Voxceleb1
use_tb_logger: true
model: sr
distortion: sr
scale: 8
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: VoxCeleb1
    mode: VoxCeleb1
    dataroot_GT: /data2/lbxie/Superface/sisr_train_128_wval.lmdb
    dataroot_LQ: /data2/lbxie/Superface/sisr_train_16_wval.lmdb
    dataroot_landmark: /data2/lbxie/Superface/sisr_train_256_landmark

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 8
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: VoxCeleb1_test
    mode: LQGT
    GT_size: 128
    dataroot_GT: /data2/lbxie/Superface/sisr_val_128
    dataroot_LQ: /data2/lbxie/Superface/sisr_val_16

#### network structures
network_G:
  which_model_G: JASRNet
  n_Parts: 68
  n_resblocks: 32
  n_feats: 128
  scale: 8
  rgb_range: 1
  n_colors: 3

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 5e-5
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.999
  epsilon: 1e-8
  weight_decay_G: 0.0005
  lr_gamma: 0.5
  niter: 1000000
  warmup_iter: -1  # no warm up
  T_period: [400000, 600000, 800000]
  clear_state: False

  pixel_criterion: L1_Loss
  pixel_weight: 1.0
  landmark_criterion: CPM
  landmark_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
